name: Package
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  package:
    runs-on: windows-latest
    strategy:
      matrix:
        mod_variant:
          - name: Default
            args: ''
            suffix: ''
          - name: WithAdditionalCraftingRecipes
            args: '--with-additional-crafting-recipes'
          - name: WithoutIncreasedEnemyVitality
            args: '--without-increased-enemy-vitality'
        translation_variant:
          - name: Official
            args: ''
          - name: Fixed
            args: '--with-russian-translation-fixes'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64

      - name: Pack
        shell: cmd
        run: ./pack.cmd ${{ matrix.mod_variant.args }} ${{ matrix.translation_variant.args }}

      - name: Get filename
        id: get-filename
        shell: pwsh
        run: |
          $file = Get-ChildItem output\*.pak | Select-Object -First 1
          if ($file) {
            echo "FILENAME=$($file.BaseName)" >> $env:GITHUB_OUTPUT
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get-filename.outputs.FILENAME }}
          path: output\
          if-no-files-found: error
